// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VYhyeXfui_i-qoeK6_131EhYigeqoN8',
    appId: '1:110544389552:web:bcc7f82b3260478b7e4275',
    messagingSenderId: '110544389552',
    projectId: 'scoreboard-186e0',
    authDomain: 'scoreboard-186e0.firebaseapp.com',
    storageBucket: 'scoreboard-186e0.firebasestorage.app',
    measurementId: 'G-MYEDW9Z85C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcqWXa6-8rb4dJIcD2rlaFgXLdHwMTmOw',
    appId: '1:110544389552:android:b9d16463209e36967e4275',
    messagingSenderId: '110544389552',
    projectId: 'scoreboard-186e0',
    storageBucket: 'scoreboard-186e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuc4MTS-s83qK4-PaZ7v8wHykNODlUxg',
    appId: '1:110544389552:ios:b87caa2c4e196bff7e4275',
    messagingSenderId: '110544389552',
    projectId: 'scoreboard-186e0',
    storageBucket: 'scoreboard-186e0.firebasestorage.app',
    iosBundleId: 'com.example.scoreBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALuc4MTS-s83qK4-PaZ7v8wHykNODlUxg',
    appId: '1:110544389552:ios:b87caa2c4e196bff7e4275',
    messagingSenderId: '110544389552',
    projectId: 'scoreboard-186e0',
    storageBucket: 'scoreboard-186e0.firebasestorage.app',
    iosBundleId: 'com.example.scoreBoard',
  );
}
